# Java
java_version=25

# Loader
obfuscated_minecraft=false
minecraft_version=26.1.2
compatible_minecraft_versions=["26.1", "26.1.1", "26.1.2"]
fabric_loader_version=0.18.4
access_widener_version=26_1
mc_publish_dependencies_list=["placeholder-api@3.0.0+26.1 (embedded)"]

# Mod dependencies
sgui_version=2.0.0+26.1
placeholder_api_version=3.0.0+26.1
luckperms_api_version=5.4
common_economy_api_version=2.0.0
