# Java
java_version=25

# Loader
obfuscated_minecraft=false
minecraft_version=26.2
compatible_minecraft_versions=["26.2"]
fabric_loader_version=0.19.3
access_widener_version=26_2
mc_publish_dependencies_list=["placeholder-api@3.1.0-beta.1+26.2 (embedded)"]

# Mod dependencies
sgui_version=2.1.0+26.2
placeholder_api_version=3.1.0-beta.1+26.2
luckperms_api_version=5.5
common_economy_api_version=2.0.0
