project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_TOKEN
base_path: .

preserve_hierarchy: true

files:
  - source: src/main/resources/io/github/sakurawald/lang/en_US.json
    translation: crowdin/%locale_with_underscore%.json


