# Configure gradle.
org.gradle.jvmargs=-Xmx4G -Xms1G -XX:+UseG1GC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.console=verbose

# Project Info.
maven_group=io.github.sakurawald
mod_id=fuji
mod_version=14.10.0

# Common dependencies.
junit_version=5.10.2
lombok_version=1.18.42
gson_version=2.10.1
json_path_version=2.9.0
guava_version=33.3.1-jre
quartz_version=2.5.0
classgraph_version=4.8.184
manifold_version=2026.1.6
errorprone_version=2.41.0
errorprone_annotations_version=2.28.0
autoservice_version=1.1.1
jetbrains_annotations_version=26.0.2
log4j_version=2.24.1

# Define the target Minecraft version. (Used by pre-processor)
mcVer=26.2