name: build
on: [ pull_request, push ]
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        java: [25]
        os: [ubuntu-latest]
        target-mc-version: ["26.2", "26.1", "1.21.11", "1.21.9", "1.21.6", "1.21.5", "1.21.4", "1.21.3", "1.21", "1.20.6", "1.20.4", "1.20.2", "1.20.1"]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Crowdin action
        uses: crowdin/github-action@v2.14.0
        # If we parallel run the crowdin action, it will fail with 409 error.
        if: github.ref == 'refs/heads/dev' && matrix.target-mc-version == '26.2'
        with:
            # Define the location of crowdin.yml file.
            config: "crowdin/crowdin.yml"

            # Always push the source file to crowdin.
            upload_sources: true
            # Never pull the source file from crowdin.
            download_sources: false

            # Always pull the translation files from crowdin.
            download_translations: true
            # Never push the translation files to crowdin.
            upload_translations: false

            # Push downloaded sources to the localization branch ???
            push_sources: true
            # Push downloaded translations to the localization branch ???
            push_translations: true

            # Create a pull-request for the translations.
            create_pull_request: true
            pull_request_base_branch_name: 'dev'
            localization_branch_name: crowdin-bot
            commit_message: 'i18n: new translations from crowdin'
            pull_request_title: 'i18n: new translations from crowdin'
            pull_request_body: 'i18n: new translations from crowdin'
            pull_request_labels: 'i18n'
        env:
            GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
            CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
            CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
      - name: Check for open PRs from github actions.
        run: |
          # List all open PRs from github actions.
          prs=$(gh pr list --state open --search "author:app/github-actions" --json number --jq '.[].number')
          
          if [ -n "$prs" ]; then
            echo "Found open PR(s) from github actions: $prs"
            echo "github_actions_pr_found=true" >> $GITHUB_ENV
          else
            echo "No open PRs from github actions."
            echo "github_actions_pr_found=false" >> $GITHUB_ENV
          fi
      - name: Ensure no open PRs from github actions before publishing a new release.
        if: contains(github.event.head_commit.message, '[publish]') && env.github_actions_pr_found == 'true'
        run: |
          echo "Open PR from github-actions found. Cancelling workflow."
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
      - name: Validate gradle wrapper
        uses: gradle/actions/setup-gradle@v4
      - name: Setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: Make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build -PmcVer=${{matrix.target-mc-version}}
      - name: Capture build artifacts
        if: ${{ runner.os == 'Linux'}}
        uses: actions/upload-artifact@v4
        with:
          name: "artifact-${{matrix.target-mc-version}}"
          path: fabric/build/libs/
      - name: MC-publish action
        uses: Kir-Antipov/mc-publish@v3.3.0
        if: contains(github.event.head_commit.message, '[publish]')
        with:
          loaders:
            fabric
            quilt

          files: |
            fabric/build/libs/!(*-@(dev|sources|javadoc)).jar
            fabric/build/libs/*-@(dev|sources|javadocs).jar

          game-version-filter: any

          version-type: release

          changelog-file: CHANGELOG.md

          modrinth-id: 1TowMm2v
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"

          github-token: ${{ secrets.GITHUB_TOKEN }}

          curseforge-id: 1096649
          curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"
